version: "3.8"

services:
  db:
    image: postgres:16
    container_name: database
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DOCKER_DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cmpc_test
    
  api:
    build: ./backend
    container_name: ${DOCKER_CONTAINER_API_NAME}
    env_file: 
      - .env
    ports:
      - "${DOCKER_API_PORT}:3000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/tests:/app/tests
      - ./backend/package.json:/app/package.json
      - ./backend/package-lock.json:/app/package-lock.json
    networks:
      - cmpc_test
    depends_on:
      db:
        condition: service_healthy

networks:
  cmpc_test:
    name: ${DOCKER_NETWORK}